/**
 * The agent-to-UI contract.
 *
 * This is the single source of truth for what an agent is allowed to send to the
 * React front end. The agent does NOT render charts. It produces a structured
 * `AgentUIPayload` describing *what* to show, *what it means*, and *how* to render
 * it. A generic React renderer turns that payload into a component.
 *
 * Keep this file framework-agnostic (no React or UI-framework imports) so it can be
 * shared between the front end and any TS tooling, and mirrored 1:1 by the Python
 * pydantic models in `agent/payloads.py`.
 */

/** Every component the UI knows how to render. Adding a new visualization means
 *  adding a member here, a payload type below, and a renderer in the registry. */
export type ComponentKind =
  | "table"
  | "line_chart"
  | "bar_chart"
  | "kpi_card"
  | "risk_matrix"
  | "timeline"
  | "gantt"
  | "variance_table"
  | "fishbone";

/** Why the agent chose this view. Drives subtle UI affordances (e.g. trend lines,
 *  comparison highlighting) and is shown to the user as an "explanation" chip. */
export type UserIntent =
  | "trend_analysis"
  | "comparison"
  | "composition"
  | "distribution"
  | "ranking"
  | "status_summary"
  | "schedule"
  | "root_cause"
  | "detail_lookup";

export type StatusLevel = "good" | "warning" | "critical" | "neutral";

/** Provenance + reasoning that travels WITH the data so the UI can show "where did
 *  this come from" and "why this chart" without re-querying the agent. */
export interface PayloadMetadata {
  /** Which MCP tool / system produced the underlying data, e.g. "EVMS MCP". */
  source: string;
  /** Plain-language reason the agent picked this component. Surfaced in the UI. */
  explanation?: string;
  /** Filters the agent applied while retrieving/shaping the data. */
  filtersApplied?: Record<string, unknown>;
  /** ISO timestamp of when the data was retrieved. */
  retrievedAt?: string;
  /** Free-form notes (assumptions, caveats) for power users. */
  notes?: string;
}

/** Field mapping: tells a generic renderer which keys in `data` map to which axes
 *  / roles. This is what lets one <LineChart> render any dataset. */
export interface FieldMapping {
  x?: string;
  y?: string;
  /** Series/category splitter for grouped or multi-line charts. */
  groupBy?: string;
  /** Single numeric value field (KPI cards, gauges). */
  value?: string;
  /** Label field (categorical axis, KPI labels, risk names). */
  label?: string;
}

type Row = Record<string, unknown>;

/** Shared shape across all payloads. Component-specific payloads narrow `component`
 *  and may require extra fields. */
interface BasePayload {
  component: ComponentKind;
  /** Stable id linking this rendered artifact to its ArtifactContext in the session
   *  registry. Generated by the agent/render path if absent. See contract/artifact.ts. */
  artifactId?: string;
  title: string;
  userIntent?: UserIntent;
  data: Row[];
  fields?: FieldMapping;
  metadata: PayloadMetadata;
}

/* ------------------------------------------------------------------ */
/* Component-specific payloads (discriminated union on `component`)     */
/* ------------------------------------------------------------------ */

export interface TablePayload extends BasePayload {
  component: "table";
  /** Optional explicit column order; defaults to keys of the first row. */
  columns?: { key: string; label: string; align?: "left" | "right" | "center" }[];
}

export interface LineChartPayload extends BasePayload {
  component: "line_chart";
  fields: FieldMapping & { x: string; y: string };
  /** Optional reference line (target, threshold) e.g. CPI target of 1.0. */
  referenceLine?: { value: number; label?: string };
}

export interface BarChartPayload extends BasePayload {
  component: "bar_chart";
  fields: FieldMapping & { x: string; y: string };
  orientation?: "vertical" | "horizontal";
}

export interface KpiCardPayload extends BasePayload {
  component: "kpi_card";
  /** Each row is one KPI: { label, value, status?, delta?, unit? }. */
  data: (Row & { label: string; value: number | string; status?: StatusLevel })[];
}

export interface RiskMatrixPayload extends BasePayload {
  component: "risk_matrix";
  fields: FieldMapping & { x: string; y: string; label?: string };
  /** Grid size (default 5x5). */
  scale?: { likelihoodMax: number; impactMax: number };
}

export interface TimelinePayload extends BasePayload {
  component: "timeline";
  /** Each row: { date, title, description?, status? }. */
  data: (Row & { date: string; title: string })[];
}

export interface GanttPayload extends BasePayload {
  component: "gantt";
  /** Each row: { task, start, end, status?, percentComplete? }. */
  data: (Row & { task: string; start: string; end: string })[];
}

export interface VarianceTablePayload extends BasePayload {
  component: "variance_table";
  /** Rows with planned vs actual; renderer computes/▲▼-colors variance. */
  fields: FieldMapping & { label: string };
  columns: { key: string; label: string; kind: "plan" | "actual" | "variance" | "text" }[];
}

export interface FishbonePayload extends BasePayload {
  component: "fishbone";
  /** Problem statement at the head of the diagram. */
  problem: string;
  /** Each row: { category, cause }. Grouped into bones by category. */
  data: (Row & { category: string; cause: string })[];
}

/** The union the agent emits and the renderer consumes. */
export type AgentUIPayload =
  | TablePayload
  | LineChartPayload
  | BarChartPayload
  | KpiCardPayload
  | RiskMatrixPayload
  | TimelinePayload
  | GanttPayload
  | VarianceTablePayload
  | FishbonePayload;
