"""Pydantic mirror of the TypeScript agent-to-UI contract (src/contract/types.ts).

This is the Python-side source of truth. The agent builds these models; ADK serializes
them to JSON; CopilotKit/AG-UI carries them to React; the React renderer validates them
again with zod. Two validation layers (Python + TS) is intentional — the boundary is an
LLM and must not be trusted on either side.

Keep this in sync with src/contract/types.ts. The TS zod schema can be exported to JSON
Schema (npm run export:schema) and diffed against `AgentUIPayload.model_json_schema()`
in CI to catch drift.
"""
from __future__ import annotations

from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, Field

ComponentKind = Literal[
    "table",
    "line_chart",
    "bar_chart",
    "kpi_card",
    "risk_matrix",
    "timeline",
    "gantt",
    "variance_table",
    "fishbone",
]

UserIntent = Literal[
    "trend_analysis",
    "comparison",
    "composition",
    "distribution",
    "ranking",
    "status_summary",
    "schedule",
    "root_cause",
    "detail_lookup",
]


class PayloadMetadata(BaseModel):
    source: str = Field(..., description="MCP tool / system that produced the data, e.g. 'EVMS MCP'.")
    explanation: Optional[str] = Field(None, description="Why the agent chose this component (shown to user).")
    filtersApplied: Optional[dict[str, Any]] = None
    retrievedAt: Optional[str] = None
    notes: Optional[str] = None


class FieldMapping(BaseModel):
    x: Optional[str] = None
    y: Optional[str] = None
    groupBy: Optional[str] = None
    value: Optional[str] = None
    label: Optional[str] = None


class _Base(BaseModel):
    # Links a rendered artifact to its ArtifactContext (artifacts.py). Generated by
    # render_ui if absent. Mirror of artifactId in src/contract/types.ts.
    artifactId: Optional[str] = None
    title: str
    userIntent: Optional[UserIntent] = None
    data: list[dict[str, Any]]
    metadata: PayloadMetadata


class TablePayload(_Base):
    component: Literal["table"] = "table"
    columns: Optional[list[dict[str, str]]] = None


class LineChartPayload(_Base):
    component: Literal["line_chart"] = "line_chart"
    fields: FieldMapping
    referenceLine: Optional[dict[str, Any]] = None


class BarChartPayload(_Base):
    component: Literal["bar_chart"] = "bar_chart"
    fields: FieldMapping
    orientation: Optional[Literal["vertical", "horizontal"]] = None


class KpiCardPayload(_Base):
    component: Literal["kpi_card"] = "kpi_card"


class RiskMatrixPayload(_Base):
    component: Literal["risk_matrix"] = "risk_matrix"
    fields: FieldMapping
    scale: Optional[dict[str, int]] = None


class TimelinePayload(_Base):
    component: Literal["timeline"] = "timeline"


class GanttPayload(_Base):
    component: Literal["gantt"] = "gantt"


class VarianceTablePayload(_Base):
    component: Literal["variance_table"] = "variance_table"
    fields: FieldMapping
    columns: list[dict[str, str]]


class FishbonePayload(_Base):
    component: Literal["fishbone"] = "fishbone"
    problem: str


AgentUIPayload = Union[
    TablePayload,
    LineChartPayload,
    BarChartPayload,
    KpiCardPayload,
    RiskMatrixPayload,
    TimelinePayload,
    GanttPayload,
    VarianceTablePayload,
    FishbonePayload,
]
